### ISSUE TITLE
datasets + software?

### ISSUE THREAD

**Issue by b-schwab** [OloOcki/awesome-citygml#5]
As soon as someone has obtained the datasets, the next logical step is: What to do with it?
Should the list also include [free](https://en.wikipedia.org/wiki/Free_software) (and proprietary?) software?

**Comment by OloOcki** [comment]
Very good idea! The question is how to put it to the repo and not to overwhelm the reader :haircut:

**Comment by b-schwab** [comment]
Maybe on a separate list in the same repo like [awesome-selfhosted](https://github.com/awesome-selfhosted/awesome-selfhosted) with the [non-free](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md) list?

**Comment by OloOcki** [comment]
Yes, this a way to go! :)

**Comment by OloOcki** [comment]
Great initiative! See the software list under the subpage to this repo: 
https://github.com/OloOcki/awesome-citygml/blob/main/software.md
